version: 2
jobs:
  build:
    working_directory: ~/auth-project
    docker:
      - image: circleci/openjdk:11.0-stretch-node-browsers-legacy
    
    steps:
      - checkout
      - restore_cache:
          key: auth-project-{{ checksum "pom.xml" }}
      - run: mvn clean install  
      - save_cache:
          paths:
            - ~/.m2
          key: auth-project-{{ checksum "pom.xml" }}
